/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskTaskIdRouteImport } from './routes/task.$taskId'
import { Route as ApiUnregisterFcmTokenRouteImport } from './routes/api/unregister-fcm-token'
import { Route as ApiSyncTaskStatusRouteImport } from './routes/api/sync-task-status'
import { Route as ApiRegisterFcmTokenRouteImport } from './routes/api/register-fcm-token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnregisterFcmTokenRoute = ApiUnregisterFcmTokenRouteImport.update({
  id: '/api/unregister-fcm-token',
  path: '/api/unregister-fcm-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncTaskStatusRoute = ApiSyncTaskStatusRouteImport.update({
  id: '/api/sync-task-status',
  path: '/api/sync-task-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterFcmTokenRoute = ApiRegisterFcmTokenRouteImport.update({
  id: '/api/register-fcm-token',
  path: '/api/register-fcm-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/register-fcm-token': typeof ApiRegisterFcmTokenRoute
  '/api/sync-task-status': typeof ApiSyncTaskStatusRoute
  '/api/unregister-fcm-token': typeof ApiUnregisterFcmTokenRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/register-fcm-token': typeof ApiRegisterFcmTokenRoute
  '/api/sync-task-status': typeof ApiSyncTaskStatusRoute
  '/api/unregister-fcm-token': typeof ApiUnregisterFcmTokenRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/register-fcm-token': typeof ApiRegisterFcmTokenRoute
  '/api/sync-task-status': typeof ApiSyncTaskStatusRoute
  '/api/unregister-fcm-token': typeof ApiUnregisterFcmTokenRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/privacy'
    | '/register'
    | '/tasks'
    | '/terms'
    | '/api/register-fcm-token'
    | '/api/sync-task-status'
    | '/api/unregister-fcm-token'
    | '/task/$taskId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/privacy'
    | '/register'
    | '/tasks'
    | '/terms'
    | '/api/register-fcm-token'
    | '/api/sync-task-status'
    | '/api/unregister-fcm-token'
    | '/task/$taskId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/privacy'
    | '/register'
    | '/tasks'
    | '/terms'
    | '/api/register-fcm-token'
    | '/api/sync-task-status'
    | '/api/unregister-fcm-token'
    | '/task/$taskId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TasksRoute: typeof TasksRoute
  TermsRoute: typeof TermsRoute
  ApiRegisterFcmTokenRoute: typeof ApiRegisterFcmTokenRoute
  ApiSyncTaskStatusRoute: typeof ApiSyncTaskStatusRoute
  ApiUnregisterFcmTokenRoute: typeof ApiUnregisterFcmTokenRoute
  TaskTaskIdRoute: typeof TaskTaskIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unregister-fcm-token': {
      id: '/api/unregister-fcm-token'
      path: '/api/unregister-fcm-token'
      fullPath: '/api/unregister-fcm-token'
      preLoaderRoute: typeof ApiUnregisterFcmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-task-status': {
      id: '/api/sync-task-status'
      path: '/api/sync-task-status'
      fullPath: '/api/sync-task-status'
      preLoaderRoute: typeof ApiSyncTaskStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register-fcm-token': {
      id: '/api/register-fcm-token'
      path: '/api/register-fcm-token'
      fullPath: '/api/register-fcm-token'
      preLoaderRoute: typeof ApiRegisterFcmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TasksRoute: TasksRoute,
  TermsRoute: TermsRoute,
  ApiRegisterFcmTokenRoute: ApiRegisterFcmTokenRoute,
  ApiSyncTaskStatusRoute: ApiSyncTaskStatusRoute,
  ApiUnregisterFcmTokenRoute: ApiUnregisterFcmTokenRoute,
  TaskTaskIdRoute: TaskTaskIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
