/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskTaskIdRouteImport } from './routes/task.$taskId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/tanstack-query',
  path: '/tanstack-query',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/drizzle',
  path: '/drizzle',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/api/tq-todos',
  path: '/api/tq-todos',
  getParentRoute: () => DemoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/tasks': typeof TasksRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/tasks': typeof TasksRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/tasks': typeof TasksRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/tasks'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/task/$taskId'
    | '/demo/api/tq-todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/tasks'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/task/$taskId'
    | '/demo/api/tq-todos'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/tasks'
    | '/demo/drizzle'
    | '/demo/tanstack-query'
    | '/task/$taskId'
    | '/demo/api/tq-todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  TasksRoute: typeof TasksRoute
  TaskTaskIdRoute: typeof TaskTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof DemoRouteRoute
    }
  }
}

interface DemoRouteRouteChildren {
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  TasksRoute: TasksRoute,
  TaskTaskIdRoute: TaskTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
