/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskTaskIdRouteImport } from './routes/task.$taskId'
import { Route as ApiTestPushRouteImport } from './routes/api/test-push'
import { Route as ApiSyncTaskStatusRouteImport } from './routes/api/sync-task-status'
import { Route as ApiRegisterFcmTokenRouteImport } from './routes/api/register-fcm-token'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestPushRoute = ApiTestPushRouteImport.update({
  id: '/api/test-push',
  path: '/api/test-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncTaskStatusRoute = ApiSyncTaskStatusRouteImport.update({
  id: '/api/sync-task-status',
  path: '/api/sync-task-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterFcmTokenRoute = ApiRegisterFcmTokenRouteImport.update({
  id: '/api/register-fcm-token',
  path: '/api/register-fcm-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/api/register-fcm-token': typeof ApiRegisterFcmTokenRoute
  '/api/sync-task-status': typeof ApiSyncTaskStatusRoute
  '/api/test-push': typeof ApiTestPushRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/api/register-fcm-token': typeof ApiRegisterFcmTokenRoute
  '/api/sync-task-status': typeof ApiSyncTaskStatusRoute
  '/api/test-push': typeof ApiTestPushRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/api/register-fcm-token': typeof ApiRegisterFcmTokenRoute
  '/api/sync-task-status': typeof ApiSyncTaskStatusRoute
  '/api/test-push': typeof ApiTestPushRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/register'
    | '/tasks'
    | '/api/register-fcm-token'
    | '/api/sync-task-status'
    | '/api/test-push'
    | '/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/register'
    | '/tasks'
    | '/api/register-fcm-token'
    | '/api/sync-task-status'
    | '/api/test-push'
    | '/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/register'
    | '/tasks'
    | '/api/register-fcm-token'
    | '/api/sync-task-status'
    | '/api/test-push'
    | '/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TasksRoute: typeof TasksRoute
  ApiRegisterFcmTokenRoute: typeof ApiRegisterFcmTokenRoute
  ApiSyncTaskStatusRoute: typeof ApiSyncTaskStatusRoute
  ApiTestPushRoute: typeof ApiTestPushRoute
  TaskTaskIdRoute: typeof TaskTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-push': {
      id: '/api/test-push'
      path: '/api/test-push'
      fullPath: '/api/test-push'
      preLoaderRoute: typeof ApiTestPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-task-status': {
      id: '/api/sync-task-status'
      path: '/api/sync-task-status'
      fullPath: '/api/sync-task-status'
      preLoaderRoute: typeof ApiSyncTaskStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register-fcm-token': {
      id: '/api/register-fcm-token'
      path: '/api/register-fcm-token'
      fullPath: '/api/register-fcm-token'
      preLoaderRoute: typeof ApiRegisterFcmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TasksRoute: TasksRoute,
  ApiRegisterFcmTokenRoute: ApiRegisterFcmTokenRoute,
  ApiSyncTaskStatusRoute: ApiSyncTaskStatusRoute,
  ApiTestPushRoute: ApiTestPushRoute,
  TaskTaskIdRoute: TaskTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
